name: Cloud Deployment Workflow

on:
  workflow_dispatch:
    inputs:

      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

      app_version:
        description: "Application version"
        required: true
        default: "1.0.0"
        type: string

      run_tests:
        description: "Run tests before deployment?"
        required: false
        default: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Display input values
        run: |
          echo "Environment : ${{ github.event.inputs.environment }}"
          echo "App Version : ${{ github.event.inputs.app_version }}"
          echo "Run Tests   : ${{ github.event.inputs.run_tests }}"
          
      - name : "Deploy dev - ${{ github.event.inputs.app_version }}"
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: |
          echo "Deploying to <${{ github.event.inputs.environment}}> with version <${{ github.event.inputs.app_version }}>"
          
      - name : Deploy staging - ${{ github.event.inputs.app_version }}
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: |
          echo "Deploying to <${{ github.event.inputs.environment}}> with version <${{ github.event.inputs.app_version }}>"
          
      - name : Deploy prod - ${{ github.event.inputs.app_version }}
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          echo "Deploying to <${{ github.event.inputs.environment}}> with version <${{ github.event.inputs.app_version }}>"
          
